mekaproject/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.my_view, name='home')
]

mekaproject/mekaproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

mekaproject/main/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name="Имя")
    email = models.EmailField(verbose_name="Email")
    phone = models.CharField(max_length=15, verbose_name="Телефон", blank=True, null=True)
    message = models.TextField(verbose_name="Сообщение")

    def __str__(self):
        return self.name

mekaproject/main/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'message']

mekaproject/main/views.py
from django.shortcuts import render


def my_view(request):
    return render(request, 'main/home.html')

mekaproject/main/templates/main/home.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>Портфолио</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles.css' %}">
    <style>
        img {
            width: 300px;
            height: 300px;
            border-radius: 100%;
        {
    </style>
</head>
<body>
    <header>
        <h1></h1>
    </header>
    <nav>
        <ul>
            <li><a href="/">Главная</a></li>
            <li><a href="/портфолио">Портфолио</a></li>
        </ul>
    </nav>
<main class="cyrot">
    <img src="{% static 'main/img/meka.jpg' %}" alt="">
    <div class="divbek">
        <h1 class="name">Привет! Я Мээризат</h1>
        <p class="description">Я занимаюсь веб-разработкой и готов показать вам мои проекты!</p>
    </div>

</main>
    <div class="mane">
        <div class="contact-form">
        <h2>Свяжитесь со мной</h2>
        <form method="post" action="{% url 'home' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Имя:</label>
                <input type="text" name="name" id="id_name" required>
            </div>
            <div class="form-group">
                <label for="id_email">Email:</label>
                <input type="email" name="email" id="id_email" required>
            </div>
            <div class="form-group">
                <label for="id_phone">Телефон:</label>
                <input type="text" name="phone" id="id_phone">
            </div>
            <div class="form-group">
                <label for="id_message">Сообщение:</label>
                <textarea name="message" id="id_message" required></textarea>
            </div>
            <button class="optn" type="submit">Отправить</button>
        </form>
    </div>

    </div>


</body>
</html>